export const GET_HOME_VIDEOS = "GET_HOME_VIDEOS";
export const GET_SEARCH_VIDEOS = "GET_SEARCH_VIDEOS";
export const LOADING_VIDEOS = "LOADING_VIDEOS";
export const VIDEO_FETCH_SUCCESS = "VIDEO_FETCH_SUCCESS";
export const VIDEO_FETCH_FAIL = "VIDEO_FETCH_FAIL";
