export const GET_HOME_VIDEOS = "GET_HOME_VIDEOS";
export const LOADING_VIDEOS = "LOADING_VIDEOS";
export const VIDEO_FETCH_SUCCESS = "VIDEO_FETCH_SUCCESS";
export const VIDEO_FETCH_FAIL = "VIDEO_FETCH_FAIL";

export const GET_SEARCH_VIDEOS = "GET_SEARCH_VIDEOS";
export const LOADING_SEARCH_VIDEOS = "LOADING_SEARCH_VIDEOS";
export const VIDEO_SEARCH_SUCCESS = "VIDEO_SEARCH_SUCCESS";
export const VIDEO_SEARCH_FAIL = "VIDEO_SEARCH_FAIL";
