export const GET_HOME_VIDEOS = "GET_HOME_VIDEOS";
export const LOADING_VIDEOS = "LOADING_VIDEOS";
export const VIDEO_FETCH_SUCCESS = "VIDEO_FETCH_SUCCESS";
export const VIDEO_FETCH_FAIL = "VIDEO_FETCH_FAIL";

export const GET_SEARCH_VIDEOS = "GET_SEARCH_VIDEOS";
export const LOADING_SEARCH_VIDEOS = "LOADING_SEARCH_VIDEOS";
export const VIDEO_SEARCH_SUCCESS = "VIDEO_SEARCH_SUCCESS";
export const VIDEO_SEARCH_FAIL = "VIDEO_SEARCH_FAIL";

export const GET_WATCH_SEARCH_VIDEOS = "GET_WATCH_SEARCH_VIDEOS";
export const LOADING_WATCH_SEARCH_VIDEOS = "LOADING_WATCH_SEARCH_VIDEOS";
export const VIDEO_WATCH_SEARCH_SUCCESS = "VIDEO_WATCH_SEARCH_SUCCESS";
export const VIDEO_WATCH_SEARCH_FAIL = "VIDEO_WATCH_SEARCH_FAIL";

export const GET_WATCH_VIDEO_DETAIL = "GET_WATCH_VIDEO_DETAIL";
export const LOADING_WATCH_VIDEO_DETAIL = "LOADING_WATCH_VIDEO_DETAIL";
export const WATCH_VIDEO_DETAIL_SUCCESS = "WATCH_VIDEO_DETAIL_SUCCESS";
export const WATCH_VIDEO_DETAIL_FAIL = "WATCH_VIDEO_DETAIL_FAIL";
